#!/bin/bash

#-----------
# Configurations
#-----------

ELIXIR_VERSION=${ELIXIR_VERSION-v1.0.0}
ELIXIR_MODE=${ELIXIR_MODE-docker}
ELIXIR_LAUNCHER_DIR=${ELIXIR_LAUNCHER_DIR-/var/local/elixir/$ELIXIR_VERSION}

#-----------
# Install Script
#-----------

echo "Install Elixir ($ELIXIR_VERSION)..."

mkdir -p ${ELIXIR_LAUNCHER_DIR}

if [[ "$ELIXIR_MODE" == "docker" ]]; then
  echo "  -- deploying via docker"
  cp ./submodules/elixir/files/elixir.dockerfile ${ELIXIR_LAUNCHER_DIR}/Dockerfile
  sed -i s/@ELIXIR_VERSION@/$ELIXIR_VERSION/g ${ELIXIR_LAUNCHER_DIR}/Dockerfile

  printf "%b" "
  .git
  .gitignore
  gitattributes
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  LEGAL
  LICENSE
  README.md
  RELEASE.md
  " > $ELIXIR_LAUNCHER_DIR/.dockerignore

  (cd ${ELIXIR_LAUNCHER_DIR} && docker build -t elixir_${ELIXIR_VERSION} .)

  echo "docker run -i -t elixir_${ELIXIR_VERSION} /bin/bash" > ${ELIXIR_LAUNCHER_DIR}/debug
  chmod 755 ${ELIXIR_LAUNCHER_DIR}/debug

else
  echo "  -- deploying directly with bash"

  cp ./submodules/elixir/files/elixir.bashfile ${ELIXIR_LAUNCHER_DIR}/Bashfile
  sed -i s/@ELIXIR_VERSION@/$ELIXIR_VERSION/g ${ELIXIR_LAUNCHER_DIR}/Bashfile
  chmod 755 ${ELIXIR_LAUNCHER_DIR}/Bashfile
  ${ELIXIR_LAUNCHER_DIR}/Bashfile

  echo "iex" > ${ELIXIR_LAUNCHER_DIR}/debug
  chmod 755 ${ELIXIR_LAUNCHER_DIR}/debug
fi

echo "DONE, Install Elixir."